language: python 
python: 
        - "2.7"
        - "3.7"

install: 
        - pip install .  
        - pip install pytest

script:
        - python example/complex_scalar_star_solver.py
        - python example/complex_vector_star_selfinteracting_solver.py
        - pytest
